# Pipeline to check code

on: pull_request

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Get Code 
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create build directory
      run: mkdir build

    - name: Compile the solution
      run: msbuild eagcfg.sln -t:rebuild -property:Configuration=Release -property:Platform=x64

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with: 
        name: eagfcfg
        path: Release