# Pipeline to check code

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Get Code 
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create build directory
      run: mkdir build

    - name: Compile the solution
      run: msbuild eagcfg.sln -t:rebuild -property:Configuration=Release